apiVersion: v1
kind: Secret
metadata:
  name: laboratoire-secret
  namespace: medinsight
type: Opaque
stringData:
  DB_PASSWORD: ${DB_PASSWORD}
  KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: laboratoire-config
  namespace: medinsight
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/medinsight_platform
  SPRING_DATASOURCE_USERNAME: admin
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8180
  KEYCLOAK_REALM: medinsight-realm
  KEYCLOAK_RESOURCE: laboratoire-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laboratoire-service
  namespace: medinsight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laboratoire-service
  template:
    metadata:
      labels:
        app: laboratoire-service
    spec:
      containers:
      - name: laboratoire-service
        image: boughanmiasma/pds:service-laboratoire
        ports:
        - containerPort: 8081
        envFrom:
        - configMapRef:
            name: laboratoire-config
        env:
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: laboratoire-secret
              key: DB_PASSWORD
        - name: KEYCLOAK_CREDENTIALS_SECRET
          valueFrom:
            secretKeyRef:
              name: laboratoire-secret
              key: KEYCLOAK_CLIENT_SECRET
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: laboratoire-service
  namespace: medinsight
spec:
  selector:
    app: laboratoire-service
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP
