name: CI/CD Microservices Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-docker-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
         service:
           - MedInsight-Microservices/dossier-service
           - MedInsight-Microservices/lab-service
           - MedInsight-Microservices/ordonnance-service
           - staff-service
   

    steps:
      #  Checkout repo
      - uses: actions/checkout@v3

      #  Setup Java
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'

      #  Build Maven
      - name: Build ${{ matrix.service }}
        working-directory: ./${{ matrix.service }}
        run: mvn clean package

      #  Login Docker
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #  Build & Push Docker Image
      - name: Build & Push ${{ matrix.service }}
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.service }}
          push: true
          tags: monuser/${{ matrix.service | split('/')[-1] }}:latest
