name: CI/CD Microservices Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-docker-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - MedInsight-Microservices/dossier-service
          - MedInsight-Microservices/lab-service
          - MedInsight-Microservices/ordonnance-service
          - staff-service
    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v3

      # 2️⃣ Setup Java
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'

      # 3️⃣ Build Maven
      - name: Build ${{ matrix.service }}
        working-directory: ./${{ matrix.service }}
        run: mvn clean package

      # 4️⃣ Login Docker
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5️⃣ Build & Push Docker Image
      - name: Build & Push ${{ matrix.service }}
        run: |
          SERVICE_NAME=$(basename ${{ matrix.service }})
          docker build -t monuser/$SERVICE_NAME:latest ${{ matrix.service }}
          docker push monuser/$SERVICE_NAME:latest
